// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    {
      type: 'autogenerated',
      dirName: '.', // '.' means the current docs folder
    },
    {
      type: 'category',
      label: 'Community',
      items: [
        {
          type: 'link',
          label: 'Rindo on GitHub',
          href: 'https://github.com/familyjs/rindo',
        },
      ],
    },
    {
      type: 'category',
      label: 'Legal',
      items: [
        {
          type: 'doc',
          id: 'telemetry',
        },
      ],
    },
  ],
};

module.exports = sidebars;
