name: Check Markdown links

on:
  pull_request:
    branches:
      - '**'

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@83b7061638ee4956cf7545a6f7efe594e5ad0247 # v3.5.1

    - name: setup node
      uses: actions/setup-node@e33196f7422957bea03ed53f6fbb155025ffc7b8 # v3.7.0
      with:
        cache: 'npm'

    - name: install dependencies
      run: npm ci

    - name: check internal markdown links
      run: npm run check-links
